---
title: "pull4_dataclean"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


read in the data
```{r}
websci<-read.csv("/Users/joycepak/Documents/UNC\ Chapel\ Hill/PCORI\ RA/5.30.21\ Data\ Pull/webofsci.csv")
websci<-websci[,c(1,2,7)]
pubmed<-read.csv("/Users/joycepak/Documents/UNC\ Chapel\ Hill/PCORI\ RA/5.30.21\ Data\ Pull/pubmed.csv")
pubmed<-pubmed[c(1:40),] #capture all trials that are from 4/1/21

pubmed_notitle<-read.csv("/Users/joycepak/Documents/UNC\ Chapel\ Hill/PCORI\ RA/5.30.21\ Data\ Pull/pubmed_notitle.csv")
pubmed_notitle<-pubmed_notitle[c(1:154),] #capture all trials that are from 4/1/21

```

read in data from 6/9/21
```{r}
pubmed1_addon<-read.csv("/Users/joycepak/Documents/UNC\ Chapel\ Hill/PCORI\ RA/5.30.21\ Data\ Pull/pubmed1.csv")
pubmed1_addon<-pubmed1_addon[c(1:6),] #capture all trials that are from 6/3/21

pubmed1_notitle_addon<-read.csv("/Users/joycepak/Documents/UNC\ Chapel\ Hill/PCORI\ RA/5.30.21\ Data\ Pull/pubmed1_notitle.csv")
pubmed1_notitle_addon<-pubmed1_notitle_addon[c(1:14),] #capture all trials that are from 4/1/21

```


```{r}
websci1<-dplyr::filter(websci, grepl('trial|Trial', Title)) #title with trial
websci2<-dplyr::filter(websci1, !grepl('protocol|Protocol|plan', Title)) #get rid of protocol
websci3<-dplyr::filter(websci2, !grepl('JAN|DEC|FEB|MAR', Publication.Date)) #get before 2/1/21

pubmed1<-dplyr::filter(pubmed, grepl('trial|Trial', Title)) #title with trial
pubmed2<-dplyr::filter(pubmed1, !grepl('protocol|Protocol|plan', Title)) #get rid of protocol

pubmed1_notitle<-dplyr::filter(pubmed_notitle, !grepl('protocol|Protocol|plan', Title)) #get rid of protocol

```

```{r}
pm_combine<-merge(pubmed2,pubmed1_notitle, by="Title",all=T)
colnames(websci3)[which(names(websci3) == "Article.Title")] <- "Title"
combine<-merge(websci3,pm_combine,by="Title",all=T)
combine1<-combine[!duplicated(combine$Title), ] #get rid of duplicate titles
```

```{r}
library(openxlsx)
write.xlsx(combine1, "/Users/joycepak/Documents/UNC\ Chapel\ Hill/PCORI\ RA/3.31.21\ Data\ Pull/websci_pubmed_combine.xlsx")
```

